import type { Scenario } from "./types";

/**
 * System scenario presets — shared across all users, hardcoded in the app.
 * User-created scenarios live in the `scenarios` Supabase table.
 */
export const SYSTEM_SCENARIOS: Scenario[] = [
  {
    id: "sys-crash",
    user_id: null,
    name: "Market crash",
    description: "All −20% · IV +50% · +1w",
    target_date: null,
    underlying_shocks: {},
    default_shock: { mode: "pct", val: -20 },
    iv_shock: { mode: "mult", val: 1.5 },
    advance_days: 7,
    interest_rate: 0.045,
    notes: null,
    created_at: "",
    updated_at: "",
    is_preset: true,
  },
  {
    id: "sys-rally",
    user_id: null,
    name: "Rally",
    description: "All +10% · IV −20%",
    target_date: null,
    underlying_shocks: {},
    default_shock: { mode: "pct", val: 10 },
    iv_shock: { mode: "mult", val: 0.8 },
    advance_days: 0,
    interest_rate: 0.045,
    notes: null,
    created_at: "",
    updated_at: "",
    is_preset: true,
  },
  {
    id: "sys-theta",
    user_id: null,
    name: "Time decay only",
    description: "No move · +30d",
    target_date: null,
    underlying_shocks: {},
    default_shock: null,
    iv_shock: { mode: "mult", val: 1.0 },
    advance_days: 30,
    interest_rate: 0.045,
    notes: null,
    created_at: "",
    updated_at: "",
    is_preset: true,
  },
  {
    id: "sys-vix",
    user_id: null,
    name: "VIX spike",
    description: "IV +100% · no move",
    target_date: null,
    underlying_shocks: {},
    default_shock: null,
    iv_shock: { mode: "mult", val: 2.0 },
    advance_days: 0,
    interest_rate: 0.045,
    notes: null,
    created_at: "",
    updated_at: "",
    is_preset: true,
  },
  {
    id: "sys-earnings",
    user_id: null,
    name: "Earnings cascade",
    description: "±exp move · IV crush 40%",
    target_date: null,
    underlying_shocks: {},
    default_shock: null,
    iv_shock: { mode: "mult", val: 0.6 },
    advance_days: 1,
    interest_rate: 0.045,
    notes: null,
    created_at: "",
    updated_at: "",
    is_preset: true,
  },
  {
    id: "sys-worst",
    user_id: null,
    name: "Next exp. worst",
    description: "Pin at worst strike",
    target_date: null,
    underlying_shocks: {},
    default_shock: null,
    iv_shock: { mode: "mult", val: 1.0 },
    advance_days: 28,
    interest_rate: 0.045,
    notes: null,
    created_at: "",
    updated_at: "",
    is_preset: true,
  },
];
